import enum

class Category(str, enum.Enum):
    alcoholic_beverages = 'Đồ uống có cồn'
    beverages = 'Đồ uống'
    cakes = 'Bánh ngọt'
    candies = 'Kẹo'
    cereals_grains = 'Ngũ cốc và hạt'
    cold_cuts = 'Thịt nguội, xúc xích và giăm bông'
    dried_fruits = 'Trái cây sấy khô'
    fresh_fruits = 'Trái cây tươi'
    fresh_meat = 'Thịt tươi'
    fruit_jams = 'Mứt trái cây'
    grains_staples = 'Lương thực'
    icecream_cheese = 'Kem và phô mai'
    instant_foods = 'Thực phẩm ăn liền'
    milk = 'Sữa'
    others = 'Khác'
    seafood_fishballs = 'Hải sản và cá viên'
    seasonings = 'Gia vị'
    snacks = 'Đồ ăn vặt'
    vegetables = 'Rau củ'
    yogurt = 'Sữa chua'