"""Initial migration

Revision ID: d73c783c4f81
Revises: 
Create Date: 2025-10-29 09:48:06.620041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd73c783c4f81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('head_masters')
    op.add_column('classrooms', sa.Column('classroom_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('classrooms', sa.Column('room_number', sa.String(length=20), nullable=False))
    op.add_column('classrooms', sa.Column('building_name', sa.String(length=100), nullable=False))
    op.drop_column('classrooms', 'name')
    op.drop_column('classrooms', 'id')
    op.add_column('course_registrations', sa.Column('registration_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('course_registrations', sa.Column('registration_time', sa.DateTime(), nullable=False))
    op.add_column('course_registrations', sa.Column('status', sa.Enum('REGISTERED', 'FULLED', 'CANCELLED', name='registrationstatus'), nullable=False))
    op.alter_column('course_registrations', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('course_registrations', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('course_registrations_student_id_fkey'), 'course_registrations', type_='foreignkey')
    op.drop_constraint(op.f('course_registrations_course_id_fkey'), 'course_registrations', type_='foreignkey')
    op.create_foreign_key(None, 'course_registrations', 'courses', ['course_id'], ['course_id'])
    op.create_foreign_key(None, 'course_registrations', 'students', ['student_id'], ['student_id'])
    op.drop_column('course_registrations', 'id')
    op.add_column('courses', sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('courses', sa.Column('semester', sa.String(length=50), nullable=False))
    op.add_column('courses', sa.Column('max_students', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('lecturer_id', sa.String(length=20), nullable=True))
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'courses', 'lecturers', ['lecturer_id'], ['lecturer_id'])
    op.create_foreign_key(None, 'courses', 'subjects', ['subject_id'], ['subject_id'])
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'id')
    op.create_foreign_key(None, 'curriculum_subjects', 'curriculums', ['curriculum_id'], ['curriculum_id'])
    op.create_foreign_key(None, 'curriculum_subjects', 'subjects', ['subject_id'], ['subject_id'])
    op.create_foreign_key(None, 'curriculums', 'lecturers', ['lecturer_id'], ['lecturer_id'])
    op.add_column('lecturers', sa.Column('lecturer_id', sa.String(length=20), nullable=False))
    op.add_column('lecturers', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('lecturers', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('lecturers', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('lecturers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('lecturers', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'lecturers', ['user_id'])
    op.create_foreign_key(None, 'lecturers', 'addresses', ['address_id'], ['address_id'])
    op.add_column('students', sa.Column('student_id', sa.String(length=20), nullable=False))
    op.add_column('students', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('class_name', sa.String(length=20), nullable=False))
    op.add_column('students', sa.Column('address_id', sa.Integer(), nullable=True))
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('students', 'major',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('students', 'enrollment_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.create_foreign_key(None, 'students', 'addresses', ['address_id'], ['address_id'])
    op.drop_column('students', 'address')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'department')
    op.drop_column('students', 'class_id')
    op.add_column('subjects', sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('subjects', sa.Column('subject_code', sa.String(length=20), nullable=False))
    op.add_column('subjects', sa.Column('credits', sa.Integer(), nullable=False))
    op.add_column('subjects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('subjects', sa.Column('department', sa.String(length=255), nullable=True))
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'subjects', ['subject_code'])
    op.drop_constraint(op.f('subjects_course_id_fkey'), 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'id')
    op.drop_column('subjects', 'course_id')
    op.add_column('timetables', sa.Column('timetable_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('timetables', sa.Column('day_of_week', sa.String(length=15), nullable=False))
    op.add_column('timetables', sa.Column('course_id', sa.Integer(), nullable=False))
    op.alter_column('timetables', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               nullable=False)
    op.alter_column('timetables', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               nullable=False)
    op.drop_constraint(op.f('timetables_subject_id_fkey'), 'timetables', type_='foreignkey')
    op.drop_constraint(op.f('timetables_lecturer_id_fkey'), 'timetables', type_='foreignkey')
    op.drop_constraint(op.f('timetables_classroom_id_fkey'), 'timetables', type_='foreignkey')
    op.create_foreign_key(None, 'timetables', 'classrooms', ['classroom_id'], ['classroom_id'])
    op.create_foreign_key(None, 'timetables', 'courses', ['course_id'], ['course_id'])
    op.drop_column('timetables', 'lecturer_id')
    op.drop_column('timetables', 'subject_id')
    op.drop_column('timetables', 'id')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'user_role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'STUDENT', 'LECTURER', 'HEADMASTER', name='userrole'),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'user_role',
               existing_type=sa.Enum('ADMIN', 'STUDENT', 'LECTURER', 'HEADMASTER', name='userrole'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.add_column('timetables', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('timetables', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetables', sa.Column('lecturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.create_foreign_key(op.f('timetables_classroom_id_fkey'), 'timetables', 'classrooms', ['classroom_id'], ['id'])
    op.create_foreign_key(op.f('timetables_lecturer_id_fkey'), 'timetables', 'lecturers', ['lecturer_id'], ['user_id'])
    op.create_foreign_key(op.f('timetables_subject_id_fkey'), 'timetables', 'subjects', ['subject_id'], ['id'])
    op.alter_column('timetables', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('timetables', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('timetables', 'course_id')
    op.drop_column('timetables', 'day_of_week')
    op.drop_column('timetables', 'timetable_id')
    op.add_column('subjects', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('subjects_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_foreign_key(op.f('subjects_course_id_fkey'), 'subjects', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'subjects', type_='unique')
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('subjects', 'department')
    op.drop_column('subjects', 'description')
    op.drop_column('subjects', 'credits')
    op.drop_column('subjects', 'subject_code')
    op.drop_column('subjects', 'subject_id')
    op.add_column('students', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'enrollment_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'major',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('students', 'address_id')
    op.drop_column('students', 'class_name')
    op.drop_column('students', 'email')
    op.drop_column('students', 'student_id')
    op.drop_constraint(None, 'lecturers', type_='foreignkey')
    op.drop_constraint(None, 'lecturers', type_='unique')
    op.drop_column('lecturers', 'address_id')
    op.drop_column('lecturers', 'email')
    op.drop_column('lecturers', 'phone_number')
    op.drop_column('lecturers', 'department')
    op.drop_column('lecturers', 'title')
    op.drop_column('lecturers', 'lecturer_id')
    op.drop_constraint(None, 'curriculums', type_='foreignkey')
    op.drop_constraint(None, 'curriculum_subjects', type_='foreignkey')
    op.drop_constraint(None, 'curriculum_subjects', type_='foreignkey')
    op.add_column('courses', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('courses', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('courses', 'lecturer_id')
    op.drop_column('courses', 'subject_id')
    op.drop_column('courses', 'max_students')
    op.drop_column('courses', 'semester')
    op.drop_column('courses', 'course_id')
    op.add_column('course_registrations', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'course_registrations', type_='foreignkey')
    op.drop_constraint(None, 'course_registrations', type_='foreignkey')
    op.create_foreign_key(op.f('course_registrations_course_id_fkey'), 'course_registrations', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('course_registrations_student_id_fkey'), 'course_registrations', 'students', ['student_id'], ['user_id'])
    op.alter_column('course_registrations', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course_registrations', 'student_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('course_registrations', 'status')
    op.drop_column('course_registrations', 'registration_time')
    op.drop_column('course_registrations', 'registration_id')
    op.add_column('classrooms', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('classrooms_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('classrooms', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('classrooms', 'building_name')
    op.drop_column('classrooms', 'room_number')
    op.drop_column('classrooms', 'classroom_id')
    op.create_table('head_masters',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('head_masters_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('head_masters_pkey'))
    )
    # ### end Alembic commands ###
