"""add image_url, description, prep_time, cook_time columns to recipes

Revision ID: 059653cddd90
Revises: f39896d5f811
Create Date: 2025-11-12 05:50:09.611515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059653cddd90'
down_revision: Union[str, Sequence[str], None] = 'f39896d5f811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipe_components_type'), 'recipe_components', ['type'], unique=False)
    op.add_column('recipes', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('prep_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('cook_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'description')
    op.drop_column('recipes', 'cook_time')
    op.drop_column('recipes', 'prep_time')
    op.drop_column('recipes', 'image_url')
    op.drop_index(op.f('ix_recipe_components_type'), table_name='recipe_components')
    # ### end Alembic commands ###
