"""remove bulk_ingredients

Revision ID: cd3e7c8f4548
Revises: 0032eb5e60f5
Create Date: 2025-11-15 01:57:51.296712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3e7c8f4548'
down_revision: Union[str, Sequence[str], None] = '0032eb5e60f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bulk_ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_ingredients',
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['uncountable_ingredients.component_id'], name=op.f('bulk_ingredients_component_id_fkey')),
    sa.PrimaryKeyConstraint('component_id', name=op.f('bulk_ingredients_pkey'))
    )
    # ### end Alembic commands ###
