"""create initial tables

Revision ID: f39896d5f811
Revises: 
Create Date: 2025-11-12 05:15:24.970947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39896d5f811'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_components',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('component_id'),
    sa.UniqueConstraint('component_name')
    )
    op.create_table('ingredients',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('estimated_shelf_life', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('estimated_price', sa.Integer(), nullable=True),
    sa.Column('ingredient_tag_list', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['recipe_components.component_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('recipes',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('default_servings', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['recipe_components.component_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('component_lists',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['recipe_components.component_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.component_id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'component_id')
    )
    op.create_table('countable_ingredients',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('c_measurement_unit', sa.Enum('QUA', 'CU', 'GOI', 'BO', 'MIENG', 'NHANH', 'TEP', name='cmeasurementunit'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['ingredients.component_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('uncountable_ingredients',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('uc_measurement_unit', sa.Enum('G', 'KG', 'ML', 'L', 'TSP', 'TBSP', 'CUP', name='ucmeasurementunit'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['ingredients.component_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('bulk_ingredients',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['uncountable_ingredients.component_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bulk_ingredients')
    op.drop_table('uncountable_ingredients')
    op.drop_table('countable_ingredients')
    op.drop_table('component_lists')
    op.drop_table('recipes')
    op.drop_table('ingredients')
    op.drop_table('recipe_components')
    # ### end Alembic commands ###
