"""create_initial_tables.py

Revision ID: 0429a20649e0
Revises: 
Create Date: 2025-12-19 06:38:24.831016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0429a20649e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('assigner_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('shopping_list', sa.JSON(), nullable=False),
    sa.Column('plan_status', sa.Enum('CREATED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='planstatus'), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('storages',
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('storage_name', sa.String(), nullable=False),
    sa.Column('storage_type', sa.Enum('FRIDGE', 'FREEZER', 'PANTRY', 'BULK_STORAGE', name='storagetype'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('storage_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_content', sa.JSON(), nullable=False),
    sa.Column('spent_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['shopping_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('storable_units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('package_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_quantity', sa.Float(), nullable=True),
    sa.Column('content_unit', sa.Enum('G', 'ML', name='ucmeasurementunit'), nullable=True),
    sa.Column('added_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(content_type = 'countable_ingredient' AND  content_quantity IS NULL AND content_unit IS NULL) OR (content_type = 'uncountable_ingredient' AND  content_quantity IS NOT NULL AND content_unit IS NOT NULL)", name='quantity_unit_required_for_measurable'),
    sa.CheckConstraint('(component_id IS NULL AND content_type IS NULL) OR (component_id IS NOT NULL AND content_type IS NOT NULL)', name='component_id_type_pairing'),
    sa.CheckConstraint('reserved_quantity <= package_quantity', name='reserved_le_package'),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.storage_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storable_units')
    op.drop_table('reports')
    op.drop_table('storages')
    op.drop_table('shopping_plans')
    # ### end Alembic commands ###
