"""storage name nullable

Revision ID: 4c4b333c878c
Revises: 7412ce2848a5
Create Date: 2025-12-31 14:25:07.366573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4b333c878c'
down_revision: Union[str, Sequence[str], None] = '7412ce2848a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storages', 'storage_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storages', 'storage_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
