"""remove reserved_quantity

Revision ID: 7412ce2848a5
Revises: df0f9cd611af
Create Date: 2025-12-28 14:53:01.605882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7412ce2848a5'
down_revision: Union[str, Sequence[str], None] = 'df0f9cd611af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storable_units', 'reserved_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storable_units', sa.Column('reserved_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
