"""unit added_date expiration_date

Revision ID: 84d1d6ceee65
Revises: f123456789ab
Create Date: 2026-01-12 05:05:09.091748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d1d6ceee65'
down_revision: Union[str, Sequence[str], None] = 'f123456789ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_plans_deadline'), table_name='shopping_plans')
    op.drop_index(op.f('ix_shopping_plans_group_id'), table_name='shopping_plans')
    op.drop_index(op.f('ix_shopping_plans_last_modified'), table_name='shopping_plans')
    op.drop_index(op.f('ix_shopping_plans_plan_status'), table_name='shopping_plans')
    op.alter_column('storable_units', 'added_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('storable_units', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_index(op.f('ix_storable_units_component_id'), table_name='storable_units')
    op.drop_index(op.f('ix_storable_units_storage_id'), table_name='storable_units')
    op.drop_index(op.f('ix_storable_units_unit_name'), table_name='storable_units')
    op.drop_index(op.f('ix_storages_group_id'), table_name='storages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_storages_group_id'), 'storages', ['group_id'], unique=False)
    op.create_index(op.f('ix_storable_units_unit_name'), 'storable_units', ['unit_name'], unique=False)
    op.create_index(op.f('ix_storable_units_storage_id'), 'storable_units', ['storage_id'], unique=False)
    op.create_index(op.f('ix_storable_units_component_id'), 'storable_units', ['component_id'], unique=False)
    op.alter_column('storable_units', 'expiration_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('storable_units', 'added_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_shopping_plans_plan_status'), 'shopping_plans', ['plan_status'], unique=False)
    op.create_index(op.f('ix_shopping_plans_last_modified'), 'shopping_plans', ['last_modified'], unique=False)
    op.create_index(op.f('ix_shopping_plans_group_id'), 'shopping_plans', ['group_id'], unique=False)
    op.create_index(op.f('ix_shopping_plans_deadline'), 'shopping_plans', ['deadline'], unique=False)
    # ### end Alembic commands ###
