"""add indexes 2

Revision ID: 91c40ba78999
Revises: 84d1d6ceee65
Create Date: 2026-01-15 14:52:20.613451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c40ba78999'
down_revision: Union[str, Sequence[str], None] = '84d1d6ceee65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reports_plan_id_key'), 'reports', type_='unique')
    op.create_index(op.f('ix_reports_plan_id'), 'reports', ['plan_id'], unique=True)
    op.create_index(op.f('ix_shopping_plans_deadline'), 'shopping_plans', ['deadline'], unique=False)
    op.create_index(op.f('ix_shopping_plans_group_id'), 'shopping_plans', ['group_id'], unique=False)
    op.create_index(op.f('ix_shopping_plans_plan_status'), 'shopping_plans', ['plan_status'], unique=False)
    op.create_index(op.f('ix_storable_units_component_id'), 'storable_units', ['component_id'], unique=False)
    op.create_index(op.f('ix_storable_units_expiration_date'), 'storable_units', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_storable_units_storage_id'), 'storable_units', ['storage_id'], unique=False)
    op.create_index(op.f('ix_storable_units_unit_name'), 'storable_units', ['unit_name'], unique=False)
    op.create_index(op.f('ix_storages_group_id'), 'storages', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storages_group_id'), table_name='storages')
    op.drop_index(op.f('ix_storable_units_unit_name'), table_name='storable_units')
    op.drop_index(op.f('ix_storable_units_storage_id'), table_name='storable_units')
    op.drop_index(op.f('ix_storable_units_expiration_date'), table_name='storable_units')
    op.drop_index(op.f('ix_storable_units_component_id'), table_name='storable_units')
    op.drop_index(op.f('ix_shopping_plans_plan_status'), table_name='shopping_plans')
    op.drop_index(op.f('ix_shopping_plans_group_id'), table_name='shopping_plans')
    op.drop_index(op.f('ix_shopping_plans_deadline'), table_name='shopping_plans')
    op.drop_index(op.f('ix_reports_plan_id'), table_name='reports')
    op.create_unique_constraint(op.f('reports_plan_id_key'), 'reports', ['plan_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
