"""add others

Revision ID: df0f9cd611af
Revises: 0429a20649e0
Create Date: 2025-12-19 07:28:10.984153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0f9cd611af'
down_revision: Union[str, Sequence[str], None] = '0429a20649e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_plans', sa.Column('others', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_plans', 'others')
    # ### end Alembic commands ###
