"""update user service schemas

Revision ID: fb7c7f6757be
Revises: c040c062b7cf
Create Date: 2025-12-24 11:07:14.746351+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb7c7f6757be'
down_revision: Union[str, Sequence[str], None] = 'c040c062b7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_memberships')
    op.drop_table('user_tags')
    op.drop_table('user_health_profiles')
    op.drop_table('user_identity_profiles')
    op.drop_table('family_groups')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('addresses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('system_role', postgresql.ENUM('ADMIN', 'USER', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('phone_num', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('email', name='uq_users_email', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('password_hash', name='uq_users_password_hash', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone_num', name='uq_users_phone_num', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name='uq_users_username', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('addresses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('ward', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_addresses'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_health_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('height_cm', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('activity_level', postgresql.ENUM('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activitylevel'), autoincrement=False, nullable=True),
    sa.Column('curr_condition', postgresql.ENUM('NORMAL', 'PREGNANT', 'INJURED', name='healthcondition'), autoincrement=False, nullable=True),
    sa.Column('health_goal', postgresql.ENUM('LOSE_WEIGHT', 'MAINTAIN', 'GAIN_WEIGHT', name='healthgoal'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_health_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_health_profiles'))
    )
    op.create_table('family_groups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('group_avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_family_groups_created_by_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_family_groups'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_tags',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_user_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id', name=op.f('pk_user_tags'))
    )
    op.create_table('group_memberships',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('HEAD_CHEF', 'MEMBER', name='grouprole'), autoincrement=False, nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('jointed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], name=op.f('fk_group_memberships_added_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['family_groups.id'], name=op.f('fk_group_memberships_group_id_family_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_group_memberships'))
    )
    op.create_table('user_identity_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='usergender'), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_user_identity_profiles_address_id_addresses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identity_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_identity_profiles'))
    )
    op.create_table('tags',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tag_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('tag_name', name=op.f('uq_tags_tag_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
