# microservices/user-service/alembic/versions/2025_11_17_0413-c040c062b7cf_initial_database_commit.py

"""initial database commit

Revision ID: c040c062b7cf
Revises: 
Create Date: 2025-11-17 04:13:27.756816+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c040c062b7cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('tag_category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('tag_name', name=op.f('uq_tags_tag_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('system_role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('phone_num', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('password_hash', name=op.f('uq_users_password_hash')),
    sa.UniqueConstraint('phone_num', name=op.f('uq_users_phone_num')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('family_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('group_avatar_url', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_family_groups_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_groups'))
    )
    op.create_table('user_health_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activitylevel'), nullable=True),
    sa.Column('curr_condition', sa.Enum('NORMAL', 'PREGNANT', 'INJURED', name='healthcondition'), nullable=True),
    sa.Column('health_goal', sa.Enum('LOSE_WEIGHT', 'MAINTAIN', 'GAIN_WEIGHT', name='healthgoal'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_health_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_health_profiles'))
    )
    op.create_table('user_identity_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='usergender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_user_identity_profiles_address_id_addresses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identity_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_identity_profiles'))
    )
    op.create_table('user_tags',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_user_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id', name=op.f('pk_user_tags'))
    )
    op.create_table('group_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('HEAD_CHEF', 'MEMBER', name='grouprole'), nullable=False),
    sa.Column('added_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('jointed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], name=op.f('fk_group_memberships_added_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['family_groups.id'], name=op.f('fk_group_memberships_group_id_family_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_group_memberships'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_memberships')
    op.drop_table('user_tags')
    op.drop_table('user_identity_profiles')
    op.drop_table('user_health_profiles')
    op.drop_table('family_groups')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('addresses')
    # ### end Alembic commands ###
