"""upgrade_user_service_schema_v2

Revision ID: cffbc8170d44
Revises: fb7c7f6757be
Create Date: 2025-12-24 16:55:15.356246+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffbc8170d44'
down_revision: Union[str, Sequence[str], None] = 'fb7c7f6757be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
