"""add keywords and change JSON to JSONB

Revision ID: 1781ee3e1613
Revises: b0716e225a1e
Create Date: 2025-12-31 04:07:17.321864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from psycopg2.extensions import JSONB
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1781ee3e1613'
down_revision: Union[str, Sequence[str], None] = 'b0716e225a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'ingredient_tag_list',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('recipes',
                  sa.Column('keywords',
                            postgresql.JSONB(astext_type=sa.Text()),
                            nullable=False,
                            server_default=sa.text("'[]'::jsonb"))
                  )
    op.alter_column('recipes', 'instructions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'instructions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('recipes', 'keywords')
    op.alter_column('ingredients', 'ingredient_tag_list',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
