"""standardize string and JSONB fields for recommender

Revision ID: 3c9be40ccf27
Revises: 1781ee3e1613
Create Date: 2025-12-31 05:27:44.331225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c9be40ccf27'
down_revision: Union[str, Sequence[str], None] = '1781ee3e1613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('component_existence', 'component_name_list',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('group_preferences', 'group_tag_list',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('tag_relations', sa.Column('user_tag_name', sa.String(), nullable=False))
    op.add_column('tag_relations', sa.Column('ingredient_tag_name', sa.String(), nullable=False))
    op.alter_column('tag_relations', 'user_tag',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tag_relations', 'ingredient_tag',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag_relations', 'ingredient_tag',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('tag_relations', 'user_tag',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('tag_relations', 'ingredient_tag_name')
    op.drop_column('tag_relations', 'user_tag_name')
    op.alter_column('group_preferences', 'group_tag_list',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('component_existence', 'component_name_list',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
