"""add indexes 2

Revision ID: 560b660b96cc
Revises: 938918bf7c02
Create Date: 2026-01-15 14:49:04.542811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '560b660b96cc'
down_revision: Union[str, Sequence[str], None] = '938918bf7c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_component_lists_component_id'), 'component_lists', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_lists_recipe_id'), 'component_lists', ['recipe_id'], unique=False)
    op.drop_constraint(op.f('countable_ingredients_component_name_key'), 'countable_ingredients', type_='unique')
    op.drop_index(op.f('ix_countable_ingredients_component_name_trgm'), table_name='countable_ingredients', postgresql_ops={'component_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_countable_ingredients_component_name'), 'countable_ingredients', ['component_name'], unique=False)
    op.create_unique_constraint('unique_countable_ingredient', 'countable_ingredients', ['component_name', 'c_measurement_unit'])
    op.add_column('group_preferences', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('group_preferences', sa.Column('user_tag_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_group_preferences_group_id'), 'group_preferences', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_preferences_user_id'), 'group_preferences', ['user_id'], unique=False)
    op.drop_column('group_preferences', 'group_tag_list')
    op.drop_index(op.f('ix_recipes_component_name_trgm'), table_name='recipes', postgresql_ops={'component_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_recipes_keywords_gin'), table_name='recipes', postgresql_using='gin')
    op.create_index('ix_recipes_keywords', 'recipes', ['keywords'], unique=False, postgresql_using='gin', postgresql_ops={'keywords': 'jsonb_path_ops'})
    op.drop_index(op.f('ix_uncountable_ingredients_component_name_trgm'), table_name='uncountable_ingredients', postgresql_ops={'component_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_uncountable_ingredients_component_name'), 'uncountable_ingredients', ['component_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uncountable_ingredients_component_name'), table_name='uncountable_ingredients')
    op.create_index(op.f('ix_uncountable_ingredients_component_name_trgm'), 'uncountable_ingredients', ['component_name'], unique=False, postgresql_ops={'component_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('ix_recipes_keywords', table_name='recipes', postgresql_using='gin', postgresql_ops={'keywords': 'jsonb_path_ops'})
    op.create_index(op.f('ix_recipes_keywords_gin'), 'recipes', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_recipes_component_name_trgm'), 'recipes', ['component_name'], unique=False, postgresql_ops={'component_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('group_preferences', sa.Column('group_tag_list', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_group_preferences_user_id'), table_name='group_preferences')
    op.drop_index(op.f('ix_group_preferences_group_id'), table_name='group_preferences')
    op.drop_column('group_preferences', 'user_tag_list')
    op.drop_column('group_preferences', 'user_id')
    op.drop_constraint('unique_countable_ingredient', 'countable_ingredients', type_='unique')
    op.drop_index(op.f('ix_countable_ingredients_component_name'), table_name='countable_ingredients')
    op.create_index(op.f('ix_countable_ingredients_component_name_trgm'), 'countable_ingredients', ['component_name'], unique=False, postgresql_ops={'component_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_unique_constraint(op.f('countable_ingredients_component_name_key'), 'countable_ingredients', ['component_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_component_lists_recipe_id'), table_name='component_lists')
    op.drop_index(op.f('ix_component_lists_component_id'), table_name='component_lists')
    # ### end Alembic commands ###
