"""add component_existence group_preferences tag_relations

Revision ID: b0716e225a1e
Revises: 88b0157da878
Create Date: 2025-12-28 14:46:28.866198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0716e225a1e'
down_revision: Union[str, Sequence[str], None] = '88b0157da878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_existence',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('component_name_list', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group_preferences',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_tag_list', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('tag_relations',
    sa.Column('user_tag', sa.Integer(), nullable=False),
    sa.Column('ingredient_tag', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_tag', 'ingredient_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_relations')
    op.drop_table('group_preferences')
    op.drop_table('component_existence')
    # ### end Alembic commands ###
