"""recipe flattened 2

Revision ID: d9f50d70ec50
Revises: 560b660b96cc
Create Date: 2026-01-16 08:05:27.156962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9f50d70ec50'
down_revision: Union[str, Sequence[str], None] = '560b660b96cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_flattened',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('all_ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['recipes.component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.alter_column('ingredients', 'ingredient_tag_list',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'ingredient_tag_list',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_table('recipes_flattened')
    # ### end Alembic commands ###
