"""create initial tables

Revision ID: 025c38f150d8
Revises: 
Create Date: 2025-12-28 15:08:48.295132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025c38f150d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', name='mealtype'), nullable=False),
    sa.Column('meal_status', sa.Enum('CREATED', 'DONE', 'CANCELLED', 'EXPIRED', name='mealstatus'), nullable=False),
    sa.PrimaryKeyConstraint('meal_id'),
    sa.UniqueConstraint('date', 'meal_type', name='unique_meal_date_type')
    )
    op.create_table('recipe_lists',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'meal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_lists')
    op.drop_table('meals')
    # ### end Alembic commands ###
