"""change group_id from int to uuid

Revision ID: 95368ef785de
Revises: 2486565d29d7
Create Date: 2026-01-06 22:06:59.529353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95368ef785de'
down_revision: Union[str, Sequence[str], None] = '2486565d29d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meals', 'group_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='gen_random_uuid()')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Lưu ý: Downgrade từ UUID về INTEGER sẽ mất dữ liệu
    op.alter_column('meals', 'group_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='1')
