"""fix unique constraint

Revision ID: ed6e6e4d08bc
Revises: 95368ef785de
Create Date: 2026-01-16 10:22:54.991402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6e6e4d08bc'
down_revision: Union[str, Sequence[str], None] = '95368ef785de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_meal_date_type'), 'meals', type_='unique')
    op.create_unique_constraint('unique_meal_date_group_type', 'meals', ['date', 'meal_type', 'group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_meal_date_group_type', 'meals', type_='unique')
    op.create_unique_constraint(op.f('unique_meal_date_type'), 'meals', ['date', 'meal_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
